TE-10998 Replaced static URL sign secret with ENV key
spryker/silexphp pull request #41
Opened 2022-04-18 11:24 UTC by dmytro-dymarchuk

## PR Description

TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2022-04-18 13:25 UTC, yaroslav-spryker approved these changes

2022-04-18 13:34 UTC, dimitriyTsemma approved these changes

2022-04-19 08:47 UTC, demkos requested changes
I'm not working on this bugfix, so please remove my name from PR

2022-04-19 08:47 UTC, demkos commented on src/Silex/Provider/HttpFragmentServiceProvider.php
> +        $this->uriSignerSecret = getenv('SPRYKER_ZED_REQUEST_TOKEN') ?: null;
This env variable is a part of Spryker, and cannot be used in SIlex lib.
Also, a fix for this module was already provided.
Please, read the expected behavior from the ticket carefully.

2022-04-22 07:50 UTC, demkos reviewed
Please, provide the release table for this PR

2022-04-25 13:35 UTC, dmytro-dymarchuk commented
> Please, provide the release table for this PR

These changes look like merge only. There are only changes in CI and tests which we usually don't describe in changelogs.

2022-07-06 12:18 UTC, floriankraemer commented
This was removed from the original RG because this is no longer directly related to the ticket.

2022-07-06 15:22 UTC, asmarovydlo commented
Closed because of https://github.com/spryker/silexphp/pull/41#issuecomment-1176152385
Can be re-opened if necessary and linked to the new ticket.

2022-07-06 15:22 UTC, closed without merging